version: '3'

services:

  inference:
      image: thonybossa/taller4_mlops:fastapi
      container_name: inference
      deploy:
        mode: replicated
        replicas: 1

        resources:
          limits:
            cpus: '2'
            memory: 500M
          reservations:
            cpus: '0.25'
            memory: 200M
      ports:
        - '8084:8085'
      restart: always
      networks:
      - network1

networks:
  network1:
      name: proyecto_2_default
      external: true