version: '3.8'

services:

  minio:
    container_name: Minio
    command: server /data --console-address ":8089" --address :8088
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    image: quay.io/minio/minio:latest
    ports:
      #- '8088:8088'
      - '8089:8089'
    expose:
      - 8088
    volumes:
      - ./minio_data:/data
    restart: always
    networks:
      - network2

volumes:
  minio_data:

networks:
  network2:
    name: proyecto_3_default
    external: true


