version: '3.8'

services:
  tfx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ${PWD}:/tfx/src
    stdin_open: true
    tty: true
    restart: "no"
